pipeline {
    agent any

    environment {
        cluster = 'vprostaging1'
        service = 'vproappstagesvc'
    }

    stages {
        stage('Deploy to ECS Prod') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
}
